import { Inter } from 'next/font/google'
import Footer from './components/footer/Footer'
import NavbarHome from './components/navbar/NavbarHome'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavbarHome />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
